services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    # environment:
      # - DB_HOST=${DB_HOST}
      # - DB_PORT=3306
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
      - /app/tmp
    # depends_on:
    # - db
  sass:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - sass_node_modules:/app/node_modules
    command: sh -c "npm install && npm run watch:css"

volumes:
  sass_node_modules:

